FROM scratch

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 build/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 build/quarkus-app/*.jar /deployments/
COPY --chown=185 build/quarkus-app/app/ /deployments/app/
COPY --chown=185 build/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Xmx16m"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
ENV PATH="/usr/bin"

ENTRYPOINT [ "/usr/bin/java","-Dquarkus.http.host=0.0.0.0", "-Djava.util.logging.manager=org.jboss.logmanager.LogManager", "-Xmx16m", "--sun-misc-unsafe-memory-access=allow", "-jar", "/deployments/quarkus-run.jar" ]

