---
name: build

'on':
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Checkout
        uses: actions/checkout@v5
        with:
          path: homeassistant-discovery
          repository: mouse256/homeassistant-discovery

      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
      - name: Run build with Gradle Wrapper
        run: ./gradlew check -PhaDiscoveryDir=homeassistant-discovery
