---
name: build

'on':
  push:
    branches:
      - "build"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew assemble

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          platforms: linux/amd64
#          push: true
#          file: src/main/docker/Dockerfile.jvm
#          tags: |
#            mouse256/arylic-mqtt:latest
#            ghcr.io/mouse256/arylic-mqtt:latest
